spring.application.name=spring-jwt-authentication
server.port=8090

# JWT Configuration
jwt.secret=mySecretKeyForJWTGenerationAndValidationThatIsAtLeast256BitsLongForHS256Algorithm
jwt.expiration=1200000

# Logging
logging.level.root=INFO
logging.level.com.cognizant.springlearn=DEBUG
